### ISSUE TITLE
verify available helm charts for the current marketplace

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc-solutions-charts#21]
https://github.com/threefoldtech/marketplace-charts/
right now we have, let's see what is already available in helm and test them out

- [x] discourse @AhmedSa-mir moved out to the backlog
- [x] cryptpad threefoldtech/vdc#32 
- [x] taiga threefoldtech/vdc#34 
- [x] peertube @OmarElawady currently working threefoldtech/vdc#35 
- [x] mattermost @waleedhammam currently working threefoldtech/vdc#36 
- [x] gitea @ashraffouda  @RafyAmgadBenjamin threefoldtech/vdc#37 
- [x] zeroci threefoldtech/vdc-solutions-charts#19
